/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author caueg
 */
public class TelaAlteExclVendasView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaAlteExclVendasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalAltExcVendas = new javax.swing.JPanel();
        pnlTituloAltExcVendas = new javax.swing.JPanel();
        lblTituloAltExcVendas = new javax.swing.JLabel();
        pnlInfoAltExcVend = new javax.swing.JPanel();
        pnlInfoAlterExclVend = new javax.swing.JPanel();
        lblAltExcValorUniVend = new javax.swing.JLabel();
        lblAltExcIdCliVend = new javax.swing.JLabel();
        txtAltExcValorTotVend = new javax.swing.JTextField();
        txtAltExcIQuantProdVend = new javax.swing.JTextField();
        lblAltExcQuantProdVend = new javax.swing.JLabel();
        lblAltExcIdProdVend = new javax.swing.JLabel();
        txtAltExcDataVend = new javax.swing.JFormattedTextField();
        txtAltExcIdProdVend = new javax.swing.JTextField();
        txtAltExcValorUniVend = new javax.swing.JTextField();
        lblAltExcValorTotVend = new javax.swing.JLabel();
        lblAltExcDataVend = new javax.swing.JLabel();
        lblAltExcIdVend = new javax.swing.JLabel();
        lblAltExcCpfCliVend = new javax.swing.JLabel();
        txtAltExcCpfCliVend = new javax.swing.JFormattedTextField();
        txtAltExcIdVend = new javax.swing.JTextField();
        txtAltExcIdCliVend = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAltExcVendas = new javax.swing.JTable();
        pnlInfoConstVendas = new javax.swing.JPanel();
        lblInfoConsVendas = new javax.swing.JLabel();
        pnlInfoConsVendas = new javax.swing.JPanel();
        txtCpfCliCosVend = new javax.swing.JFormattedTextField();
        txtIdConsVend = new javax.swing.JTextField();
        lblIdConsVend = new javax.swing.JLabel();
        lblCpfCliConsVend = new javax.swing.JLabel();
        btnConsutarClientes1 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Alteração ou Exclusão de Venda");

        pnlPrincipalAltExcVendas.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalAltExcVendas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloAltExcVendas.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloAltExcVendas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloAltExcVendas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAltExcVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAltExcVendas.setText("Alteração ou Exclusão de Venda");

        javax.swing.GroupLayout pnlTituloAltExcVendasLayout = new javax.swing.GroupLayout(pnlTituloAltExcVendas);
        pnlTituloAltExcVendas.setLayout(pnlTituloAltExcVendasLayout);
        pnlTituloAltExcVendasLayout.setHorizontalGroup(
            pnlTituloAltExcVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAltExcVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloAltExcVendas)
                .addGap(209, 209, 209))
        );
        pnlTituloAltExcVendasLayout.setVerticalGroup(
            pnlTituloAltExcVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAltExcVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAltExcVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInfoAltExcVend.setBackground(new java.awt.Color(0, 0, 0));

        pnlInfoAlterExclVend.setBackground(new java.awt.Color(0, 0, 0));

        lblAltExcValorUniVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcValorUniVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcValorUniVend.setText("Valor unitário:");

        lblAltExcIdCliVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcIdCliVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcIdCliVend.setText("ID Cliente:");

        txtAltExcValorTotVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcValorTotVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcValorTotVend.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcValorTotVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtAltExcIQuantProdVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcIQuantProdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcIQuantProdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcIQuantProdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcQuantProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcQuantProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcQuantProdVend.setText("Quantidade Produto:");

        lblAltExcIdProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcIdProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcIdProdVend.setText("ID Produto:");

        txtAltExcDataVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcDataVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcDataVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcDataVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcDataVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtAltExcIdProdVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcIdProdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcIdProdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcIdProdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtAltExcValorUniVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcValorUniVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcValorUniVend.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcValorUniVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcValorTotVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcValorTotVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcValorTotVend.setText("Valor Total:");

        lblAltExcDataVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcDataVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcDataVend.setText("Data:");

        lblAltExcIdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcIdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcIdVend.setText("ID Venda:");

        lblAltExcCpfCliVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCpfCliVend.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCpfCliVend.setText("CPF Cliente:");

        txtAltExcCpfCliVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcCpfCliVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcCpfCliVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcCpfCliVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcCpfCliVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtAltExcIdVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcIdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcIdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcIdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtAltExcIdCliVend.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcIdCliVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcIdCliVend.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcIdCliVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        javax.swing.GroupLayout pnlInfoAlterExclVendLayout = new javax.swing.GroupLayout(pnlInfoAlterExclVend);
        pnlInfoAlterExclVend.setLayout(pnlInfoAlterExclVendLayout);
        pnlInfoAlterExclVendLayout.setHorizontalGroup(
            pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                        .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                                        .addComponent(lblAltExcCpfCliVend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAltExcCpfCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                                        .addComponent(lblAltExcIdCliVend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAltExcIdCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(174, 174, 174))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInfoAlterExclVendLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblAltExcDataVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAltExcDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                                .addComponent(lblAltExcIdProdVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAltExcIdProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAltExcValorUniVend)
                                    .addComponent(lblAltExcQuantProdVend))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAltExcIQuantProdVend)
                                    .addComponent(txtAltExcValorUniVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lblAltExcValorTotVend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltExcValorTotVend, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lblAltExcIdVend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltExcIdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInfoAlterExclVendLayout.setVerticalGroup(
            pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoAlterExclVendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcIdVend)
                    .addComponent(txtAltExcIdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcIdCliVend)
                    .addComponent(txtAltExcIdCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcIdProdVend)
                    .addComponent(txtAltExcIdProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcCpfCliVend)
                    .addComponent(txtAltExcCpfCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltExcIQuantProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcQuantProdVend))
                .addGap(38, 38, 38)
                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAltExcValorUniVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAltExcValorUniVend))
                    .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAltExcDataVend)
                        .addComponent(txtAltExcDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(pnlInfoAlterExclVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltExcValorTotVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcValorTotVend))
                .addContainerGap())
        );

        pnlInfoAlterExclVendLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAltExcDataVend, txtAltExcValorUniVend});

        pnlInfoAlterExclVendLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAltExcCpfCliVend, txtAltExcIdCliVend});

        tblAltExcVendas.setBackground(new java.awt.Color(0, 0, 0));
        tblAltExcVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Venda", "ID Cliente", "ID Produto", "CPF Cliente", "Quantidade", "Data", "Valor Unitário", "Valor Total"
            }
        ));
        tblAltExcVendas.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblAltExcVendas);

        pnlInfoConstVendas.setBackground(new java.awt.Color(0, 0, 0));

        lblInfoConsVendas.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblInfoConsVendas.setForeground(new java.awt.Color(204, 255, 204));
        lblInfoConsVendas.setText("Informe o ID da venda ou o CPF do Cliente para consulta");

        pnlInfoConsVendas.setBackground(new java.awt.Color(0, 0, 0));

        txtCpfCliCosVend.setBackground(new java.awt.Color(204, 255, 204));
        txtCpfCliCosVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtCpfCliCosVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpfCliCosVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliCosVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCpfCliCosVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCliCosVendActionPerformed(evt);
            }
        });

        txtIdConsVend.setBackground(new java.awt.Color(204, 255, 204));
        txtIdConsVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdConsVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdConsVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIdConsVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdConsVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdConsVend.setText("ID:");

        lblCpfCliConsVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCpfCliConsVend.setForeground(new java.awt.Color(204, 255, 204));
        lblCpfCliConsVend.setText("CPF Cliente:");

        btnConsutarClientes1.setBackground(new java.awt.Color(204, 255, 204));
        btnConsutarClientes1.setForeground(new java.awt.Color(0, 0, 0));
        btnConsutarClientes1.setText("Consultar");
        btnConsutarClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutarClientes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoConsVendasLayout = new javax.swing.GroupLayout(pnlInfoConsVendas);
        pnlInfoConsVendas.setLayout(pnlInfoConsVendasLayout);
        pnlInfoConsVendasLayout.setHorizontalGroup(
            pnlInfoConsVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConsVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdConsVend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdConsVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(lblCpfCliConsVend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfCliCosVend, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsutarClientes1)
                .addContainerGap())
        );
        pnlInfoConsVendasLayout.setVerticalGroup(
            pnlInfoConsVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConsVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoConsVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdConsVend)
                    .addComponent(txtIdConsVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCliConsVend)
                    .addComponent(txtCpfCliCosVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsutarClientes1))
                .addContainerGap())
        );

        pnlInfoConsVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCpfCliCosVend, txtIdConsVend});

        javax.swing.GroupLayout pnlInfoConstVendasLayout = new javax.swing.GroupLayout(pnlInfoConstVendas);
        pnlInfoConstVendas.setLayout(pnlInfoConstVendasLayout);
        pnlInfoConstVendasLayout.setHorizontalGroup(
            pnlInfoConstVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoConstVendasLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(lblInfoConsVendas)
                .addGap(174, 174, 174))
            .addGroup(pnlInfoConstVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoConsVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoConstVendasLayout.setVerticalGroup(
            pnlInfoConstVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConstVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoConsVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(pnlInfoConsVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlInfoAltExcVendLayout = new javax.swing.GroupLayout(pnlInfoAltExcVend);
        pnlInfoAltExcVend.setLayout(pnlInfoAltExcVendLayout);
        pnlInfoAltExcVendLayout.setHorizontalGroup(
            pnlInfoAltExcVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlInfoAltExcVendLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(pnlInfoAlterExclVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoAltExcVendLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlInfoConstVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        pnlInfoAltExcVendLayout.setVerticalGroup(
            pnlInfoAltExcVendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoAltExcVendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoConstVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoAlterExclVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnAlterar.setBackground(new java.awt.Color(204, 255, 204));
        btnAlterar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterar.setText("Alterar");

        btnExcluir.setBackground(new java.awt.Color(204, 255, 204));
        btnExcluir.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setText("Excluir");

        javax.swing.GroupLayout pnlPrincipalAltExcVendasLayout = new javax.swing.GroupLayout(pnlPrincipalAltExcVendas);
        pnlPrincipalAltExcVendas.setLayout(pnlPrincipalAltExcVendasLayout);
        pnlPrincipalAltExcVendasLayout.setHorizontalGroup(
            pnlPrincipalAltExcVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloAltExcVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalAltExcVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoAltExcVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalAltExcVendasLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrincipalAltExcVendasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnExcluir});

        pnlPrincipalAltExcVendasLayout.setVerticalGroup(
            pnlPrincipalAltExcVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalAltExcVendasLayout.createSequentialGroup()
                .addComponent(pnlTituloAltExcVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoAltExcVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalAltExcVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(21, 21, 21))
        );

        pnlPrincipalAltExcVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnExcluir});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsutarClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutarClientes1ActionPerformed
        if(txtIdConsVend.getText().trim().equals("") || txtCpfCliCosVend.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Informe um dos valores para consulta");
        }
        else{
            if(txtIdConsVend.getText().trim().equals("")){
                int idVendCons = Integer.parseInt(txtIdConsVend.getText());
            }
            else{
                int cpfCliCons = Integer.parseInt(txtCpfCliCosVend.getText());
            }
        }
    }//GEN-LAST:event_btnConsutarClientes1ActionPerformed

    private void txtCpfCliCosVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCliCosVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCliCosVendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlteExclVendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsutarClientes1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltExcCpfCliVend;
    private javax.swing.JLabel lblAltExcDataVend;
    private javax.swing.JLabel lblAltExcIdCliVend;
    private javax.swing.JLabel lblAltExcIdProdVend;
    private javax.swing.JLabel lblAltExcIdVend;
    private javax.swing.JLabel lblAltExcQuantProdVend;
    private javax.swing.JLabel lblAltExcValorTotVend;
    private javax.swing.JLabel lblAltExcValorUniVend;
    private javax.swing.JLabel lblCpfCliConsVend;
    private javax.swing.JLabel lblIdConsVend;
    private javax.swing.JLabel lblInfoConsVendas;
    private javax.swing.JLabel lblTituloAltExcVendas;
    private javax.swing.JPanel pnlInfoAltExcVend;
    private javax.swing.JPanel pnlInfoAlterExclVend;
    private javax.swing.JPanel pnlInfoConsVendas;
    private javax.swing.JPanel pnlInfoConstVendas;
    private javax.swing.JPanel pnlPrincipalAltExcVendas;
    private javax.swing.JPanel pnlTituloAltExcVendas;
    private javax.swing.JTable tblAltExcVendas;
    private javax.swing.JFormattedTextField txtAltExcCpfCliVend;
    private javax.swing.JFormattedTextField txtAltExcDataVend;
    private javax.swing.JTextField txtAltExcIQuantProdVend;
    private javax.swing.JTextField txtAltExcIdCliVend;
    private javax.swing.JTextField txtAltExcIdProdVend;
    private javax.swing.JTextField txtAltExcIdVend;
    private javax.swing.JTextField txtAltExcValorTotVend;
    private javax.swing.JTextField txtAltExcValorUniVend;
    private javax.swing.JFormattedTextField txtCpfCliCosVend;
    private javax.swing.JTextField txtIdConsVend;
    // End of variables declaration//GEN-END:variables
}
