/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author caueg
 */
public class TelaCadastroVendaView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaCadastroVendaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalCadasVendas = new javax.swing.JPanel();
        pnlTituloCadasVendas = new javax.swing.JPanel();
        lblTituloCadasVendas = new javax.swing.JLabel();
        pnlInfoCadasVendas = new javax.swing.JPanel();
        lblIdVend = new javax.swing.JLabel();
        txtValorUniVend = new javax.swing.JTextField();
        lblIdProdVend = new javax.swing.JLabel();
        lblCpfCliVend = new javax.swing.JLabel();
        lblDataVend = new javax.swing.JLabel();
        txtDataVend = new javax.swing.JFormattedTextField();
        lblValorUniVend = new javax.swing.JLabel();
        txtIdVend = new javax.swing.JTextField();
        txtIdProdVend = new javax.swing.JTextField();
        lblIdCliVend = new javax.swing.JLabel();
        txtIdCienteVend = new javax.swing.JTextField();
        txtCpfCliVend = new javax.swing.JFormattedTextField();
        lblQuantProdVend = new javax.swing.JLabel();
        txtQuantiadeProdVend = new javax.swing.JTextField();
        lblValorTotVend = new javax.swing.JLabel();
        txtValorTotalVend = new javax.swing.JTextField();
        btnSalvar1 = new javax.swing.JButton();
        btnSalvar2 = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlIntesSacola = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro de Venda");

        pnlPrincipalCadasVendas.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalCadasVendas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloCadasVendas.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloCadasVendas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloCadasVendas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCadasVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCadasVendas.setText("Cadastro de Venda");

        javax.swing.GroupLayout pnlTituloCadasVendasLayout = new javax.swing.GroupLayout(pnlTituloCadasVendas);
        pnlTituloCadasVendas.setLayout(pnlTituloCadasVendasLayout);
        pnlTituloCadasVendasLayout.setHorizontalGroup(
            pnlTituloCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloCadasVendasLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(lblTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(306, 306, 306))
        );
        pnlTituloCadasVendasLayout.setVerticalGroup(
            pnlTituloCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCadasVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInfoCadasVendas.setBackground(new java.awt.Color(0, 0, 0));

        lblIdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdVend.setText("ID Venda:");

        txtValorUniVend.setBackground(new java.awt.Color(204, 255, 204));
        txtValorUniVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtValorUniVend.setForeground(new java.awt.Color(0, 0, 0));
        txtValorUniVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIdProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdProdVend.setText("*ID Produto:");

        lblCpfCliVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCpfCliVend.setForeground(new java.awt.Color(204, 255, 204));
        lblCpfCliVend.setText("*CPF Cliente:");

        lblDataVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblDataVend.setForeground(new java.awt.Color(204, 255, 204));
        lblDataVend.setText("*Data:");

        txtDataVend.setBackground(new java.awt.Color(204, 255, 204));
        txtDataVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtDataVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblValorUniVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblValorUniVend.setForeground(new java.awt.Color(204, 255, 204));
        lblValorUniVend.setText("Valor unitário:");

        txtIdVend.setBackground(new java.awt.Color(204, 255, 204));
        txtIdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtIdProdVend.setBackground(new java.awt.Color(204, 255, 204));
        txtIdProdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdProdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdProdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIdCliVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdCliVend.setForeground(new java.awt.Color(204, 255, 204));
        lblIdCliVend.setText("*ID Cliente:");

        txtIdCienteVend.setBackground(new java.awt.Color(204, 255, 204));
        txtIdCienteVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdCienteVend.setForeground(new java.awt.Color(0, 0, 0));
        txtIdCienteVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtCpfCliVend.setBackground(new java.awt.Color(204, 255, 204));
        txtCpfCliVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtCpfCliVend.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpfCliVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblQuantProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblQuantProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblQuantProdVend.setText("*Quantidade Produto:");

        txtQuantiadeProdVend.setBackground(new java.awt.Color(204, 255, 204));
        txtQuantiadeProdVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtQuantiadeProdVend.setForeground(new java.awt.Color(0, 0, 0));
        txtQuantiadeProdVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblValorTotVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblValorTotVend.setForeground(new java.awt.Color(204, 255, 204));
        lblValorTotVend.setText("Valor Total:");

        txtValorTotalVend.setBackground(new java.awt.Color(204, 255, 204));
        txtValorTotalVend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtValorTotalVend.setForeground(new java.awt.Color(0, 0, 0));
        txtValorTotalVend.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        btnSalvar1.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnSalvar1.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar1.setText("Adicionar Item");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btnSalvar2.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnSalvar2.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar2.setText("Excluir Item");
        btnSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar2ActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(204, 255, 204));
        btnLimpar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoCadasVendasLayout = new javax.swing.GroupLayout(pnlInfoCadasVendas);
        pnlInfoCadasVendas.setLayout(pnlInfoCadasVendasLayout);
        pnlInfoCadasVendasLayout.setHorizontalGroup(
            pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                        .addComponent(lblCpfCliVend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCpfCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                        .addComponent(lblIdCliVend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdCienteVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(lblDataVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalvar1)
                                    .addComponent(txtDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(174, 174, 174)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addComponent(lblIdProdVend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorUniVend)
                                    .addComponent(lblQuantProdVend))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantiadeProdVend, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtValorUniVend)))))
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(lblIdVend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(lblValorTotVend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(btnSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtValorTotalVend, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoCadasVendasLayout.setVerticalGroup(
            pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdVend)
                    .addComponent(txtIdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCliVend)
                    .addComponent(txtIdCienteVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProdVend)
                    .addComponent(txtIdProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCliVend)
                    .addComponent(txtCpfCliVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantiadeProdVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantProdVend))
                .addGap(26, 26, 26)
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorUniVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorUniVend)
                    .addComponent(lblDataVend)
                    .addComponent(txtDataVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorTotalVend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorTotVend))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoCadasVendasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInfoCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar1)
                            .addComponent(btnLimpar)
                            .addComponent(btnSalvar2))
                        .addContainerGap())))
        );

        pnlInfoCadasVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDataVend, txtValorUniVend});

        pnlInfoCadasVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCpfCliVend, txtIdCienteVend});

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Finalizar compra");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        pnlIntesSacola.setBackground(new java.awt.Color(0, 0, 0));
        pnlIntesSacola.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Adicionados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        pnlIntesSacola.setForeground(new java.awt.Color(204, 255, 204));
        pnlIntesSacola.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlIntesSacola.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Venda", "ID Cliente", "ID Produto", "CPF Cliente", "Quantidade Produto", "Data", "Valor Unitário", "Valor Total"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlIntesSacolaLayout = new javax.swing.GroupLayout(pnlIntesSacola);
        pnlIntesSacola.setLayout(pnlIntesSacolaLayout);
        pnlIntesSacolaLayout.setHorizontalGroup(
            pnlIntesSacolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntesSacolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlIntesSacolaLayout.setVerticalGroup(
            pnlIntesSacolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntesSacolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalCadasVendasLayout = new javax.swing.GroupLayout(pnlPrincipalCadasVendas);
        pnlPrincipalCadasVendas.setLayout(pnlPrincipalCadasVendasLayout);
        pnlPrincipalCadasVendasLayout.setHorizontalGroup(
            pnlPrincipalCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalCadasVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalCadasVendasLayout.createSequentialGroup()
                        .addComponent(pnlInfoCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlPrincipalCadasVendasLayout.createSequentialGroup()
                        .addComponent(pnlIntesSacola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCadasVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );
        pnlPrincipalCadasVendasLayout.setVerticalGroup(
            pnlPrincipalCadasVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCadasVendasLayout.createSequentialGroup()
                .addComponent(pnlTituloCadasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoCadasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlIntesSacola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtIdCienteVend.getText().trim().equals("") || txtIdProdVend.getText().trim().equals("") || txtCpfCliVend.getText().trim().equals("") || txtQuantiadeProdVend.getText().trim().equals("") || txtDataVend.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha os campos vazios obrigatórios!");
        } else if (txtIdProdVend.getText().trim().equals("") || txtCpfCliVend.getText().trim().equals("") || txtQuantiadeProdVend.getText().trim().equals("") || txtDataVend.getText().trim().equals("")) {
            int idCliVend = Integer.parseInt(txtIdCienteVend.getText());
            JOptionPane.showMessageDialog(this, "Preencha os campos vazios obrigatórios!");
        } else if (txtCpfCliVend.getText().trim().equals("") || txtQuantiadeProdVend.getText().trim().equals("") || txtDataVend.getText().trim().equals("")) {
            int idProdVend = Integer.parseInt(txtIdProdVend.getText());
            int idCliVend = Integer.parseInt(txtIdCienteVend.getText());
            JOptionPane.showMessageDialog(this, "Preencha os campos vazios obrigatórios!");
        } else if(txtQuantiadeProdVend.getText().trim().equals("") || txtDataVend.getText().trim().equals("")) {
            int idProdVend = Integer.parseInt(txtIdProdVend.getText());
            int idCliVend = Integer.parseInt(txtIdCienteVend.getText());
            int cpfCliVend = Integer.parseInt(txtCpfCliVend.getText());
            JOptionPane.showMessageDialog(this, "Preencha os campos vazios obrigatórios!");
        } else if(txtDataVend.getText().trim().equals("")) {
            int idProdVend = Integer.parseInt(txtIdProdVend.getText());
            int idCliVend = Integer.parseInt(txtIdCienteVend.getText());
            int cpfCliVend = Integer.parseInt(txtCpfCliVend.getText());
            int qtdProdVend = Integer.parseInt(txtQuantiadeProdVend.getText());
            JOptionPane.showMessageDialog(this, "Preencha os campos vazios obrigatórios!");
        } else {
            int idProdVend = Integer.parseInt(txtIdProdVend.getText());
            int idCliVend = Integer.parseInt(txtIdCienteVend.getText());
            int cpfCliVend = Integer.parseInt(txtCpfCliVend.getText());
            int qtdProdVend = Integer.parseInt(txtQuantiadeProdVend.getText());
            int dataVend = Integer.parseInt(txtDataVend.getText());
            JOptionPane.showMessageDialog(this, "Venda cadastrada!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
            txtIdCienteVend.setText("");
            txtIdProdVend.setText("");
            txtCpfCliVend.setText("");
            txtQuantiadeProdVend.setText("");
            txtDataVend.setText("");
            txtValorUniVend.setText("");
            txtValorTotalVend.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnSalvar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCpfCliVend;
    private javax.swing.JLabel lblDataVend;
    private javax.swing.JLabel lblIdCliVend;
    private javax.swing.JLabel lblIdProdVend;
    private javax.swing.JLabel lblIdVend;
    private javax.swing.JLabel lblQuantProdVend;
    private javax.swing.JLabel lblTituloCadasVendas;
    private javax.swing.JLabel lblValorTotVend;
    private javax.swing.JLabel lblValorUniVend;
    private javax.swing.JPanel pnlInfoCadasVendas;
    private javax.swing.JPanel pnlIntesSacola;
    private javax.swing.JPanel pnlPrincipalCadasVendas;
    private javax.swing.JPanel pnlTituloCadasVendas;
    private javax.swing.JFormattedTextField txtCpfCliVend;
    private javax.swing.JFormattedTextField txtDataVend;
    private javax.swing.JTextField txtIdCienteVend;
    private javax.swing.JTextField txtIdProdVend;
    private javax.swing.JTextField txtIdVend;
    private javax.swing.JTextField txtQuantiadeProdVend;
    private javax.swing.JTextField txtValorTotalVend;
    private javax.swing.JTextField txtValorUniVend;
    // End of variables declaration//GEN-END:variables
}
