/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import static java.awt.Color.red;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author caueg
 */
public class TelaCadastroClientesView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaCadastroClientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSexoCliente = new javax.swing.ButtonGroup();
        pnlPrincipalCadasCliente = new javax.swing.JPanel();
        pnlTituloCadastroVenda = new javax.swing.JPanel();
        lblTituloCadasVenda = new javax.swing.JLabel();
        pnlInfoCadasClientes = new javax.swing.JPanel();
        lblIdCli = new javax.swing.JLabel();
        txtNumCepCli = new javax.swing.JTextField();
        lblCpfCli = new javax.swing.JLabel();
        txtCpfCli = new javax.swing.JFormattedTextField();
        lblNomeCli = new javax.swing.JLabel();
        txtLogradCli = new javax.swing.JTextField();
        lblLograCli = new javax.swing.JLabel();
        txtNomeCli = new javax.swing.JTextField();
        lblDataNascCli = new javax.swing.JLabel();
        txtDataNascCli = new javax.swing.JFormattedTextField();
        lblCepCli = new javax.swing.JLabel();
        txtCepCli = new javax.swing.JFormattedTextField();
        lblNumCepCli = new javax.swing.JLabel();
        txtIdCli = new javax.swing.JTextField();
        lblComplCli = new javax.swing.JLabel();
        txtCompleCli = new javax.swing.JTextField();
        lblCidCli = new javax.swing.JLabel();
        txtCidCli = new javax.swing.JTextField();
        lblTelCli = new javax.swing.JLabel();
        txtTelCli = new javax.swing.JFormattedTextField();
        txtSexoCli = new javax.swing.JLabel();
        rdbSexMascCli = new javax.swing.JRadioButton();
        rdbSexFemCli = new javax.swing.JRadioButton();
        lblEmailCli = new javax.swing.JLabel();
        txtEmailCli = new javax.swing.JTextField();
        lblECCli = new javax.swing.JLabel();
        cbbEstCivCli = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro de Clientes");

        pnlPrincipalCadasCliente.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalCadasCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloCadastroVenda.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloCadasVenda.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloCadasVenda.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCadasVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCadasVenda.setText("Cadastro de Clientes");

        javax.swing.GroupLayout pnlTituloCadastroVendaLayout = new javax.swing.GroupLayout(pnlTituloCadastroVenda);
        pnlTituloCadastroVenda.setLayout(pnlTituloCadastroVendaLayout);
        pnlTituloCadastroVendaLayout.setHorizontalGroup(
            pnlTituloCadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloCadastroVendaLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(lblTituloCadasVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(306, 306, 306))
        );
        pnlTituloCadastroVendaLayout.setVerticalGroup(
            pnlTituloCadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCadastroVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCadasVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInfoCadasClientes.setBackground(new java.awt.Color(0, 0, 0));

        lblIdCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdCli.setForeground(new java.awt.Color(204, 255, 204));
        lblIdCli.setText("ID:");

        txtNumCepCli.setBackground(new java.awt.Color(204, 255, 204));
        txtNumCepCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNumCepCli.setForeground(new java.awt.Color(0, 0, 0));
        txtNumCepCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblCpfCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCpfCli.setForeground(new java.awt.Color(204, 255, 204));
        lblCpfCli.setText("*CPF:");

        txtCpfCli.setBackground(new java.awt.Color(204, 255, 204));
        txtCpfCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtCpfCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpfCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCpfCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCliActionPerformed(evt);
            }
        });

        lblNomeCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblNomeCli.setForeground(new java.awt.Color(204, 255, 204));
        lblNomeCli.setText("*Nome:");

        txtLogradCli.setBackground(new java.awt.Color(204, 255, 204));
        txtLogradCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtLogradCli.setForeground(new java.awt.Color(0, 0, 0));
        txtLogradCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblLograCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblLograCli.setForeground(new java.awt.Color(204, 255, 204));
        lblLograCli.setText("*Logradouro:");

        txtNomeCli.setBackground(new java.awt.Color(204, 255, 204));
        txtNomeCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNomeCli.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblDataNascCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblDataNascCli.setForeground(new java.awt.Color(204, 255, 204));
        lblDataNascCli.setText("*Data de Nascimento:");

        txtDataNascCli.setBackground(new java.awt.Color(204, 255, 204));
        txtDataNascCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtDataNascCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataNascCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblCepCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCepCli.setForeground(new java.awt.Color(204, 255, 204));
        lblCepCli.setText("*CEP:");

        txtCepCli.setBackground(new java.awt.Color(204, 255, 204));
        txtCepCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtCepCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCepCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCepCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblNumCepCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblNumCepCli.setForeground(new java.awt.Color(204, 255, 204));
        lblNumCepCli.setText("*Numero:");

        txtIdCli.setBackground(new java.awt.Color(204, 255, 204));
        txtIdCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdCli.setForeground(new java.awt.Color(0, 0, 0));
        txtIdCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblComplCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblComplCli.setForeground(new java.awt.Color(204, 255, 204));
        lblComplCli.setText("Complemento:");

        txtCompleCli.setBackground(new java.awt.Color(204, 255, 204));
        txtCompleCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCompleCli.setForeground(new java.awt.Color(0, 0, 0));
        txtCompleCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblCidCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCidCli.setForeground(new java.awt.Color(204, 255, 204));
        lblCidCli.setText("*Cidade:");

        txtCidCli.setBackground(new java.awt.Color(204, 255, 204));
        txtCidCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCidCli.setForeground(new java.awt.Color(0, 0, 0));
        txtCidCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblTelCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblTelCli.setForeground(new java.awt.Color(204, 255, 204));
        lblTelCli.setText("*Telefone:");

        txtTelCli.setBackground(new java.awt.Color(204, 255, 204));
        txtTelCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtTelCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtTelCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtSexoCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        txtSexoCli.setForeground(new java.awt.Color(204, 255, 204));
        txtSexoCli.setText("*Sexo:");

        rdbSexMascCli.setBackground(new java.awt.Color(0, 0, 0));
        btgSexoCliente.add(rdbSexMascCli);
        rdbSexMascCli.setForeground(new java.awt.Color(204, 255, 204));
        rdbSexMascCli.setText("M");
        rdbSexMascCli.setActionCommand("M");

        rdbSexFemCli.setBackground(new java.awt.Color(0, 0, 0));
        btgSexoCliente.add(rdbSexFemCli);
        rdbSexFemCli.setForeground(new java.awt.Color(204, 255, 204));
        rdbSexFemCli.setText("F");
        rdbSexFemCli.setActionCommand("F");

        lblEmailCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblEmailCli.setForeground(new java.awt.Color(204, 255, 204));
        lblEmailCli.setText("*E-mail:");

        txtEmailCli.setBackground(new java.awt.Color(204, 255, 204));
        txtEmailCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEmailCli.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtEmailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCliActionPerformed(evt);
            }
        });

        lblECCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblECCli.setForeground(new java.awt.Color(204, 255, 204));
        lblECCli.setText("*Estado Civil:");

        cbbEstCivCli.setBackground(new java.awt.Color(204, 255, 204));
        cbbEstCivCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbbEstCivCli.setForeground(new java.awt.Color(0, 0, 0));
        cbbEstCivCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..", "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)", "União Estável" }));
        cbbEstCivCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        javax.swing.GroupLayout pnlInfoCadasClientesLayout = new javax.swing.GroupLayout(pnlInfoCadasClientes);
        pnlInfoCadasClientes.setLayout(pnlInfoCadasClientesLayout);
        pnlInfoCadasClientesLayout.setHorizontalGroup(
            pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                        .addComponent(lblEmailCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblECCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbEstCivCli, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                        .addComponent(lblComplCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCompleCli, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                            .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDataNascCli)
                                .addComponent(lblNomeCli))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                                    .addComponent(txtDataNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(386, 386, 386)
                                    .addComponent(txtSexoCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdbSexMascCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdbSexFemCli))
                                .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                            .addComponent(lblLograCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLogradCli, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(lblIdCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCpfCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                            .addComponent(lblCepCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                                    .addComponent(lblCidCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                                    .addComponent(lblTelCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(69, 69, 69)
                            .addComponent(lblNumCepCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoCadasClientesLayout.setVerticalGroup(
            pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasClientesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCli)
                    .addComponent(txtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCli)
                    .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCli)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascCli)
                    .addComponent(txtDataNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelCli)
                    .addComponent(txtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexoCli)
                    .addComponent(rdbSexMascCli)
                    .addComponent(rdbSexFemCli))
                .addGap(29, 29, 29)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCepCli)
                    .addComponent(txtNumCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidCli)
                    .addComponent(txtCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCepCli)
                    .addComponent(txtCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLograCli)
                    .addComponent(txtLogradCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplCli)
                    .addComponent(txtCompleCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoCadasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailCli)
                    .addComponent(lblECCli)
                    .addComponent(cbbEstCivCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnlInfoCadasClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbEstCivCli, txtCepCli, txtCompleCli, txtCpfCli, txtDataNascCli, txtEmailCli, txtLogradCli, txtNomeCli, txtNumCepCli, txtTelCli});

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(204, 255, 204));
        btnLimpar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalCadasClienteLayout = new javax.swing.GroupLayout(pnlPrincipalCadasCliente);
        pnlPrincipalCadasCliente.setLayout(pnlPrincipalCadasClienteLayout);
        pnlPrincipalCadasClienteLayout.setHorizontalGroup(
            pnlPrincipalCadasClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloCadastroVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalCadasClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoCadasClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalCadasClienteLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrincipalCadasClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLimpar, btnSalvar});

        pnlPrincipalCadasClienteLayout.setVerticalGroup(
            pnlPrincipalCadasClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCadasClienteLayout.createSequentialGroup()
                .addComponent(pnlTituloCadastroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoCadasClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalCadasClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar))
                .addGap(21, 21, 21))
        );

        pnlPrincipalCadasClienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLimpar, btnSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCliActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtCpfCli.getText().trim().equals("") || txtNomeCli.getText().trim().equals("") || txtDataNascCli.getText().trim().equals("") || txtTelCli.getText().trim().equals("") || rdbSexMascCli.getText().trim().equals("") || rdbSexFemCli.getText().trim().equals("") || txtCepCli.getText().trim().equals("") || txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            txtCpfCli.setBackground(Color.red);
            txtNomeCli.setBackground(Color.red);
            txtDataNascCli.setBackground(Color.red);
            txtTelCli.setBackground(Color.red);
            txtCepCli.setBackground(Color.red);
            txtCidCli.setBackground(Color.red);
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtNomeCli.getText().trim().equals("") || txtDataNascCli.getText().trim().equals("") || txtTelCli.getText().trim().equals("") || rdbSexMascCli.getText().trim().equals("") || rdbSexFemCli.getText().trim().equals("") || txtCepCli.getText().trim().equals("") || txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            txtNomeCli.setBackground(Color.red);
            txtDataNascCli.setBackground(Color.red);
            txtTelCli.setBackground(Color.red);
            txtCepCli.setBackground(Color.red);
            txtCidCli.setBackground(Color.red);
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtDataNascCli.getText().trim().equals("") || txtTelCli.getText().trim().equals("") || rdbSexMascCli.getText().trim().equals("") || rdbSexFemCli.getText().trim().equals("") || txtCepCli.getText().trim().equals("") || txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            txtDataNascCli.setBackground(Color.red);
            txtTelCli.setBackground(Color.red);
            txtCepCli.setBackground(Color.red);
            txtCidCli.setBackground(Color.red);
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtTelCli.getText().trim().equals("") || rdbSexMascCli.getText().trim().equals("") || rdbSexFemCli.getText().trim().equals("") || txtCepCli.getText().trim().equals("") || txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (rdbSexMascCli.getText().trim().equals("") || rdbSexFemCli.getText().trim().equals("") || txtCepCli.getText().trim().equals("") || txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            txtTelCli.setBackground(Color.red);
            txtCepCli.setBackground(Color.red);
            txtCidCli.setBackground(Color.red);
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtCepCli.getText().trim().equals("") || txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                char SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                char SexCli = sexx.charAt(0);
            }
            txtCepCli.setBackground(Color.red);
            txtCidCli.setBackground(Color.red);
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtCidCli.getText().trim().equals("") || txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                char SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                char SexCli = sexx.charAt(0);
            }
            int cepCli = Integer.parseInt(txtCepCli.getText());
            txtCidCli.setBackground(Color.red);
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtNumCepCli.getText().trim().equals("") || txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                char SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                char SexCli = sexx.charAt(0);
            }
            int cepCli = Integer.parseInt(txtCepCli.getText());
            String cidCli = txtCidCli.getText();
            txtNumCepCli.setBackground(Color.red);
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtLogradCli.getText().trim().equals("") || txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                char SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                char SexCli = sexx.charAt(0);
            }
            int cepCli = Integer.parseInt(txtCepCli.getText());
            String cidCli = txtCidCli.getText();
            int numCepCli = Integer.parseInt(txtNumCepCli.getText());
            txtLogradCli.setBackground(Color.red);
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if (txtEmailCli.getText().trim().equals("") || (cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                char SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                char SexCli = sexx.charAt(0);
            }
            int cepCli = Integer.parseInt(txtCepCli.getText());
            String cidCli = txtCidCli.getText();
            int numCepCli = Integer.parseInt(txtNumCepCli.getText());
            String lograCli = txtLogradCli.getText();
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else if ((cbbEstCivCli.getSelectedIndex() == 0)) {
            int cpfCli = Integer.parseInt(txtCpfCli.getText());
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                char SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                char SexCli = sexx.charAt(0);
            }
            int cepCli = Integer.parseInt(txtCepCli.getText());
            String cidCli = txtCidCli.getText();
            int numCepCli = Integer.parseInt(txtNumCepCli.getText());
            String lograCli = txtLogradCli.getText();
            String emailCli = txtEmailCli.getText();
            txtEmailCli.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!");
        } else {
            String cpfCli = txtCpfCli.getText();
            String nomeCli = txtNomeCli.getText();
            int dataNascCli = Integer.parseInt(txtDataNascCli.getText());
            int telCli = Integer.parseInt(txtTelCli.getText());
            char SexCli = 0;
            if (rdbSexMascCli.getText().trim().equals("")) {
                String sexx = rdbSexFemCli.getText();
                SexCli = sexx.charAt(0);
            } else if (rdbSexFemCli.getText().trim().equals("")) {
                String sexx = rdbSexMascCli.getText();
                SexCli = sexx.charAt(0);
            }
            int cepCli = Integer.parseInt(txtCepCli.getText());
            String cidCli = txtCidCli.getText();
            int numCepCli = Integer.parseInt(txtNumCepCli.getText());
            String lograCli = txtLogradCli.getText();
            String emailCli = txtEmailCli.getText();
            String estCivCli = cbbEstCivCli.getSelectedItem().toString();
            JOptionPane.showMessageDialog(this, "Cliente Cadastrado com Suscesso!");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCliActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtCpfCli.setText("");
        txtNomeCli.setText("");
        txtDataNascCli.setText("");
        txtTelCli.setText("");
        txtCepCli.setText("");
        txtCidCli.setText("");
        txtNumCepCli.setText("");
        txtLogradCli.setText("");
        txtCompleCli.setText("");
        txtEmailCli.setText("");
        cbbEstCivCli.setSelectedIndex(0);

    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSexoCliente;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbEstCivCli;
    private javax.swing.JLabel lblCepCli;
    private javax.swing.JLabel lblCidCli;
    private javax.swing.JLabel lblComplCli;
    private javax.swing.JLabel lblCpfCli;
    private javax.swing.JLabel lblDataNascCli;
    private javax.swing.JLabel lblECCli;
    private javax.swing.JLabel lblEmailCli;
    private javax.swing.JLabel lblIdCli;
    private javax.swing.JLabel lblLograCli;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblNumCepCli;
    private javax.swing.JLabel lblTelCli;
    private javax.swing.JLabel lblTituloCadasVenda;
    private javax.swing.JPanel pnlInfoCadasClientes;
    private javax.swing.JPanel pnlPrincipalCadasCliente;
    private javax.swing.JPanel pnlTituloCadastroVenda;
    private javax.swing.JRadioButton rdbSexFemCli;
    private javax.swing.JRadioButton rdbSexMascCli;
    private javax.swing.JFormattedTextField txtCepCli;
    private javax.swing.JTextField txtCidCli;
    private javax.swing.JTextField txtCompleCli;
    private javax.swing.JFormattedTextField txtCpfCli;
    private javax.swing.JFormattedTextField txtDataNascCli;
    private javax.swing.JTextField txtEmailCli;
    private javax.swing.JTextField txtIdCli;
    private javax.swing.JTextField txtLogradCli;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNumCepCli;
    private javax.swing.JLabel txtSexoCli;
    private javax.swing.JFormattedTextField txtTelCli;
    // End of variables declaration//GEN-END:variables
}
