/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author caueg
 */
public class TelaCadastroProdutosView extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroVendas
     */
    public TelaCadastroProdutosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgModalidade = new javax.swing.ButtonGroup();
        pnlPrincipalCadasProdutos = new javax.swing.JPanel();
        pnlTituloCadasProdutos = new javax.swing.JPanel();
        lblTituloCadasVendas = new javax.swing.JLabel();
        pnlInfoCadasProdutos = new javax.swing.JPanel();
        pnlItensProd = new javax.swing.JPanel();
        txtMarcaProd = new javax.swing.JTextField();
        lblTamanProd = new javax.swing.JLabel();
        cbbCorProd = new javax.swing.JComboBox<>();
        rdbModalidadeMasc = new javax.swing.JRadioButton();
        lblModalidade = new javax.swing.JLabel();
        txtPrecoProd = new javax.swing.JTextField();
        lblCorProd = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        lblIModeloProd = new javax.swing.JLabel();
        rdbModalidadeFem = new javax.swing.JRadioButton();
        lblQuantProdVend = new javax.swing.JLabel();
        lblIdProd = new javax.swing.JLabel();
        lblMarcaProd = new javax.swing.JLabel();
        cbbTamanhoProd = new javax.swing.JComboBox<>();
        txtModeloProd = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipalCadasProdutos.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalCadasProdutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloCadasProdutos.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloCadasVendas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloCadasVendas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloCadasVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCadasVendas.setText("Cadastro de Produto");

        javax.swing.GroupLayout pnlTituloCadasProdutosLayout = new javax.swing.GroupLayout(pnlTituloCadasProdutos);
        pnlTituloCadasProdutos.setLayout(pnlTituloCadasProdutosLayout);
        pnlTituloCadasProdutosLayout.setHorizontalGroup(
            pnlTituloCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCadasProdutosLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(lblTituloCadasVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloCadasProdutosLayout.setVerticalGroup(
            pnlTituloCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloCadasProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCadasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInfoCadasProdutos.setBackground(new java.awt.Color(0, 0, 0));

        pnlItensProd.setBackground(new java.awt.Color(0, 0, 0));

        txtMarcaProd.setBackground(new java.awt.Color(204, 255, 204));
        txtMarcaProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtMarcaProd.setForeground(new java.awt.Color(0, 0, 0));
        txtMarcaProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblTamanProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblTamanProd.setForeground(new java.awt.Color(204, 255, 204));
        lblTamanProd.setText("*Tamanho:");

        cbbCorProd.setBackground(new java.awt.Color(204, 255, 204));
        cbbCorProd.setForeground(new java.awt.Color(0, 0, 0));
        cbbCorProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Vermelho", "Azul", "Preto", "Amarelo", "Laranja", "Verde", "Rosa", "Roxo", "Marrom", "Outros..." }));

        rdbModalidadeMasc.setBackground(new java.awt.Color(0, 0, 0));
        btgModalidade.add(rdbModalidadeMasc);
        rdbModalidadeMasc.setForeground(new java.awt.Color(204, 255, 204));
        rdbModalidadeMasc.setText("Masculino");

        lblModalidade.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblModalidade.setForeground(new java.awt.Color(204, 255, 204));
        lblModalidade.setText("*Modalidade:");

        txtPrecoProd.setBackground(new java.awt.Color(204, 255, 204));
        txtPrecoProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPrecoProd.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecoProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblCorProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblCorProd.setForeground(new java.awt.Color(204, 255, 204));
        lblCorProd.setText("Cor:");

        txtIdProd.setBackground(new java.awt.Color(204, 255, 204));
        txtIdProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdProd.setForeground(new java.awt.Color(0, 0, 0));
        txtIdProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIModeloProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIModeloProd.setForeground(new java.awt.Color(204, 255, 204));
        lblIModeloProd.setText("*Modelo:");

        rdbModalidadeFem.setBackground(new java.awt.Color(0, 0, 0));
        btgModalidade.add(rdbModalidadeFem);
        rdbModalidadeFem.setForeground(new java.awt.Color(204, 255, 204));
        rdbModalidadeFem.setText("Feminino");
        rdbModalidadeFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbModalidadeFemActionPerformed(evt);
            }
        });

        lblQuantProdVend.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblQuantProdVend.setForeground(new java.awt.Color(204, 255, 204));
        lblQuantProdVend.setText("*Preço:");

        lblIdProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdProd.setForeground(new java.awt.Color(204, 255, 204));
        lblIdProd.setText("*ID Produto:");

        lblMarcaProd.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblMarcaProd.setForeground(new java.awt.Color(204, 255, 204));
        lblMarcaProd.setText("*Marca:");

        cbbTamanhoProd.setBackground(new java.awt.Color(204, 255, 204));
        cbbTamanhoProd.setForeground(new java.awt.Color(0, 0, 0));
        cbbTamanhoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "33/34", "34/35", "35/36", "36/37", "37/38", "38/39", "39/40", "40/41", "41/42", "42/43", "43/44" }));

        txtModeloProd.setBackground(new java.awt.Color(204, 255, 204));
        txtModeloProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtModeloProd.setForeground(new java.awt.Color(0, 0, 0));
        txtModeloProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        javax.swing.GroupLayout pnlItensProdLayout = new javax.swing.GroupLayout(pnlItensProd);
        pnlItensProd.setLayout(pnlItensProdLayout);
        pnlItensProdLayout.setHorizontalGroup(
            pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addComponent(lblModalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbModalidadeMasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbModalidadeFem))
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addComponent(lblMarcaProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addComponent(lblCorProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbCorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addComponent(lblIModeloProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModeloProd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTamanProd)
                                    .addComponent(lblQuantProdVend))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecoProd)
                                    .addComponent(cbbTamanhoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblIdProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlItensProdLayout.setVerticalGroup(
            pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProd)
                    .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorProd)
                            .addComponent(cbbCorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlItensProdLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIModeloProd)
                                    .addComponent(txtModeloProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuantProdVend)))
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTamanProd)
                                    .addComponent(cbbTamanhoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlItensProdLayout.createSequentialGroup()
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarcaProd)
                                    .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(pnlItensProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModalidade)
                                    .addComponent(rdbModalidadeMasc)
                                    .addComponent(rdbModalidadeFem))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlInfoCadasProdutosLayout = new javax.swing.GroupLayout(pnlInfoCadasProdutos);
        pnlInfoCadasProdutos.setLayout(pnlInfoCadasProdutosLayout);
        pnlInfoCadasProdutosLayout.setHorizontalGroup(
            pnlInfoCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoCadasProdutosLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(pnlItensProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoCadasProdutosLayout.setVerticalGroup(
            pnlInfoCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoCadasProdutosLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(pnlItensProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(204, 255, 204));
        btnLimpar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalCadasProdutosLayout = new javax.swing.GroupLayout(pnlPrincipalCadasProdutos);
        pnlPrincipalCadasProdutos.setLayout(pnlPrincipalCadasProdutosLayout);
        pnlPrincipalCadasProdutosLayout.setHorizontalGroup(
            pnlPrincipalCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloCadasProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalCadasProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoCadasProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalCadasProdutosLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pnlPrincipalCadasProdutosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLimpar, btnSalvar});

        pnlPrincipalCadasProdutosLayout.setVerticalGroup(
            pnlPrincipalCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCadasProdutosLayout.createSequentialGroup()
                .addComponent(pnlTituloCadasProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoCadasProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalCadasProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addGap(21, 21, 21))
        );

        pnlPrincipalCadasProdutosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLimpar, btnSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCadasProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    }//GEN-LAST:event_btnLimparActionPerformed

    private void rdbModalidadeFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbModalidadeFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbModalidadeFemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgModalidade;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbCorProd;
    private javax.swing.JComboBox<String> cbbTamanhoProd;
    private javax.swing.JLabel lblCorProd;
    private javax.swing.JLabel lblIModeloProd;
    private javax.swing.JLabel lblIdProd;
    private javax.swing.JLabel lblMarcaProd;
    private javax.swing.JLabel lblModalidade;
    private javax.swing.JLabel lblQuantProdVend;
    private javax.swing.JLabel lblTamanProd;
    private javax.swing.JLabel lblTituloCadasVendas;
    private javax.swing.JPanel pnlInfoCadasProdutos;
    private javax.swing.JPanel pnlItensProd;
    private javax.swing.JPanel pnlPrincipalCadasProdutos;
    private javax.swing.JPanel pnlTituloCadasProdutos;
    private javax.swing.JRadioButton rdbModalidadeFem;
    private javax.swing.JRadioButton rdbModalidadeMasc;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtMarcaProd;
    private javax.swing.JTextField txtModeloProd;
    private javax.swing.JTextField txtPrecoProd;
    // End of variables declaration//GEN-END:variables
}
