/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author caueg
 */
public class TelaAlteExclClientesView extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroClientesView
     */
    public TelaAlteExclClientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSexoCliente = new javax.swing.ButtonGroup();
        pnlPrincipalAltExcClientes = new javax.swing.JPanel();
        pnlTituloAltExcClientes = new javax.swing.JPanel();
        lblTituloAltExcClientes = new javax.swing.JLabel();
        btnAlterarClientes = new javax.swing.JButton();
        btnExcluirClientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAltExcClientes = new javax.swing.JTable();
        txtIdConsCli = new javax.swing.JTextField();
        lblIdConsCli = new javax.swing.JLabel();
        lblNomeConsCli = new javax.swing.JLabel();
        txtNomeConsCli = new javax.swing.JTextField();
        pnlInfoConsClientes = new javax.swing.JPanel();
        rbtAltExcSexFemCli = new javax.swing.JRadioButton();
        txtAltExcCidCli = new javax.swing.JTextField();
        lblAltExcTelCli = new javax.swing.JLabel();
        lblAltExcCepCli = new javax.swing.JLabel();
        lblAltExcLograCli = new javax.swing.JLabel();
        lblAltExcSexCli = new javax.swing.JLabel();
        txtAltExcNumCepCli = new javax.swing.JTextField();
        rbtAltExcSexMascCli = new javax.swing.JRadioButton();
        lblAltExcIdCli = new javax.swing.JLabel();
        lblAltExcNomeCli = new javax.swing.JLabel();
        txtAltExcCepCli = new javax.swing.JFormattedTextField();
        lblAltExcComplCli = new javax.swing.JLabel();
        txtAltExcEmailCli = new javax.swing.JTextField();
        txtAltExcIdCli = new javax.swing.JTextField();
        txtAltExcCpfCli = new javax.swing.JFormattedTextField();
        lblAltExcNumCepCli = new javax.swing.JLabel();
        txtAltExcComplCli = new javax.swing.JTextField();
        lblAltExcECCli = new javax.swing.JLabel();
        txtAltExcLograCli = new javax.swing.JTextField();
        lblAltExcCidCli = new javax.swing.JLabel();
        txtAltExcTelCli = new javax.swing.JFormattedTextField();
        txtAltExcDataNascCli = new javax.swing.JFormattedTextField();
        lblAltExcCpfCli = new javax.swing.JLabel();
        cbbAltExcECCli = new javax.swing.JComboBox<>();
        lblAltExcDataNascCli = new javax.swing.JLabel();
        txtAltExcNomeCli = new javax.swing.JTextField();
        lblAltExcEmailCli = new javax.swing.JLabel();
        lblInfoAltExcClientes = new javax.swing.JLabel();
        btnConsutarClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Alteração e Exclusão de Clientes");
        setAlwaysOnTop(true);

        pnlPrincipalAltExcClientes.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipalAltExcClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlTituloAltExcClientes.setBackground(new java.awt.Color(204, 255, 204));

        lblTituloAltExcClientes.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTituloAltExcClientes.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAltExcClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAltExcClientes.setText("Alteração e Exclusão de Clientes");

        javax.swing.GroupLayout pnlTituloAltExcClientesLayout = new javax.swing.GroupLayout(pnlTituloAltExcClientes);
        pnlTituloAltExcClientes.setLayout(pnlTituloAltExcClientesLayout);
        pnlTituloAltExcClientesLayout.setHorizontalGroup(
            pnlTituloAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloAltExcClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloAltExcClientes)
                .addGap(201, 201, 201))
        );
        pnlTituloAltExcClientesLayout.setVerticalGroup(
            pnlTituloAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloAltExcClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAltExcClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAlterarClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnAlterarClientes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnAlterarClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterarClientes.setText("Alterar");

        btnExcluirClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnExcluirClientes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnExcluirClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirClientes.setText("Excluir");

        tblAltExcClientes.setBackground(new java.awt.Color(0, 0, 0));
        tblAltExcClientes.setForeground(new java.awt.Color(204, 255, 204));
        tblAltExcClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "E-mail", "DataNasc", "Telefone", "Sexo", "CEP", "Logradouro", "Numero", "Cidade", "Complemento", "Estado Civil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAltExcClientes.setToolTipText("");
        tblAltExcClientes.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tblAltExcClientes);

        txtIdConsCli.setBackground(new java.awt.Color(204, 255, 204));
        txtIdConsCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdConsCli.setForeground(new java.awt.Color(0, 0, 0));
        txtIdConsCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblIdConsCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblIdConsCli.setForeground(new java.awt.Color(204, 255, 204));
        lblIdConsCli.setText("ID:");

        lblNomeConsCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblNomeConsCli.setForeground(new java.awt.Color(204, 255, 204));
        lblNomeConsCli.setText("Nome:");

        txtNomeConsCli.setBackground(new java.awt.Color(204, 255, 204));
        txtNomeConsCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNomeConsCli.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeConsCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        pnlInfoConsClientes.setBackground(new java.awt.Color(0, 0, 0));

        rbtAltExcSexFemCli.setBackground(new java.awt.Color(0, 0, 0));
        btgSexoCliente.add(rbtAltExcSexFemCli);
        rbtAltExcSexFemCli.setForeground(new java.awt.Color(204, 255, 204));
        rbtAltExcSexFemCli.setText("F");
        rbtAltExcSexFemCli.setActionCommand("F");

        txtAltExcCidCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcCidCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcCidCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcCidCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcTelCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcTelCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcTelCli.setText("Telefone:");

        lblAltExcCepCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCepCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCepCli.setText("CEP:");

        lblAltExcLograCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcLograCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcLograCli.setText("Logradouro:");

        lblAltExcSexCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcSexCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcSexCli.setText("Sexo:");

        txtAltExcNumCepCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcNumCepCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcNumCepCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcNumCepCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        rbtAltExcSexMascCli.setBackground(new java.awt.Color(0, 0, 0));
        btgSexoCliente.add(rbtAltExcSexMascCli);
        rbtAltExcSexMascCli.setForeground(new java.awt.Color(204, 255, 204));
        rbtAltExcSexMascCli.setText("M");
        rbtAltExcSexMascCli.setActionCommand("M");

        lblAltExcIdCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcIdCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcIdCli.setText("ID:");

        lblAltExcNomeCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcNomeCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcNomeCli.setText("Nome:");

        txtAltExcCepCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcCepCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcCepCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcCepCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcCepCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblAltExcComplCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcComplCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcComplCli.setText("Complemento:");

        txtAltExcEmailCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcEmailCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcEmailCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcEmailCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcEmailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltExcEmailCliActionPerformed(evt);
            }
        });

        txtAltExcIdCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcIdCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcIdCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcIdCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        txtAltExcCpfCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcCpfCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcCpfCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcCpfCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcCpfCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblAltExcNumCepCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcNumCepCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcNumCepCli.setText("Numero:");

        txtAltExcComplCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcComplCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcComplCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcComplCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcECCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcECCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcECCli.setText("Estado Civil:");

        txtAltExcLograCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcLograCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcLograCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcLograCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcCidCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCidCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCidCli.setText("Cidade:");

        txtAltExcTelCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcTelCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcTelCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcTelCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcTelCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtAltExcDataNascCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcDataNascCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));
        txtAltExcDataNascCli.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtAltExcDataNascCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAltExcDataNascCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblAltExcCpfCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcCpfCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcCpfCli.setText("CPF:");

        cbbAltExcECCli.setBackground(new java.awt.Color(204, 255, 204));
        cbbAltExcECCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbbAltExcECCli.setForeground(new java.awt.Color(0, 0, 0));
        cbbAltExcECCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)", "União Estável" }));
        cbbAltExcECCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcDataNascCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcDataNascCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcDataNascCli.setText("Data de Nascimento:");

        txtAltExcNomeCli.setBackground(new java.awt.Color(204, 255, 204));
        txtAltExcNomeCli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAltExcNomeCli.setForeground(new java.awt.Color(0, 0, 0));
        txtAltExcNomeCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 1, true));

        lblAltExcEmailCli.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        lblAltExcEmailCli.setForeground(new java.awt.Color(204, 255, 204));
        lblAltExcEmailCli.setText("E-mail:");

        javax.swing.GroupLayout pnlInfoConsClientesLayout = new javax.swing.GroupLayout(pnlInfoConsClientes);
        pnlInfoConsClientes.setLayout(pnlInfoConsClientesLayout);
        pnlInfoConsClientesLayout.setHorizontalGroup(
            pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                        .addComponent(lblAltExcEmailCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltExcEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblAltExcECCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbAltExcECCli, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                        .addComponent(lblAltExcComplCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAltExcComplCli, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAltExcDataNascCli)
                                .addComponent(lblAltExcNomeCli))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                                    .addComponent(txtAltExcDataNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(386, 386, 386)
                                    .addComponent(lblAltExcSexCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtAltExcSexMascCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtAltExcSexFemCli))
                                .addComponent(txtAltExcNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addComponent(lblAltExcLograCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcLograCli, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(lblAltExcIdCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAltExcCpfCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                            .addComponent(lblAltExcCepCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98)
                            .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                                    .addComponent(lblAltExcCidCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAltExcCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                                    .addComponent(lblAltExcTelCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAltExcTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(69, 69, 69)
                            .addComponent(lblAltExcNumCepCli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAltExcNumCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlInfoConsClientesLayout.setVerticalGroup(
            pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoConsClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcIdCli)
                    .addComponent(txtAltExcIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcCpfCli)
                    .addComponent(txtAltExcCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcNomeCli)
                    .addComponent(txtAltExcNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcDataNascCli)
                    .addComponent(txtAltExcDataNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcTelCli)
                    .addComponent(txtAltExcTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcSexCli)
                    .addComponent(rbtAltExcSexMascCli)
                    .addComponent(rbtAltExcSexFemCli))
                .addGap(29, 29, 29)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcNumCepCli)
                    .addComponent(txtAltExcNumCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcCidCli)
                    .addComponent(txtAltExcCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcCepCli)
                    .addComponent(txtAltExcCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcLograCli)
                    .addComponent(txtAltExcLograCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltExcComplCli)
                    .addComponent(txtAltExcComplCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoConsClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltExcEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltExcEmailCli)
                    .addComponent(lblAltExcECCli)
                    .addComponent(cbbAltExcECCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlInfoConsClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbAltExcECCli, txtAltExcCepCli, txtAltExcComplCli, txtAltExcCpfCli, txtAltExcDataNascCli, txtAltExcEmailCli, txtAltExcLograCli, txtAltExcNomeCli, txtAltExcNumCepCli, txtAltExcTelCli});

        lblInfoAltExcClientes.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        lblInfoAltExcClientes.setForeground(new java.awt.Color(204, 255, 204));
        lblInfoAltExcClientes.setText("Informe o ID ou o nome para consulta");

        btnConsutarClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnConsutarClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnConsutarClientes.setText("Consultar");
        btnConsutarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalAltExcClientesLayout = new javax.swing.GroupLayout(pnlPrincipalAltExcClientes);
        pnlPrincipalAltExcClientes.setLayout(pnlPrincipalAltExcClientesLayout);
        pnlPrincipalAltExcClientesLayout.setHorizontalGroup(
            pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloAltExcClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(pnlInfoConsClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAlterarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(btnExcluirClientes)
                                .addGap(92, 92, 92)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                                .addComponent(lblIdConsCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdConsCli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(lblNomeConsCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeConsCli, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addComponent(btnConsutarClientes)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInfoAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );

        pnlPrincipalAltExcClientesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarClientes, btnExcluirClientes});

        pnlPrincipalAltExcClientesLayout.setVerticalGroup(
            pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalAltExcClientesLayout.createSequentialGroup()
                .addComponent(pnlTituloAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInfoAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdConsCli)
                    .addComponent(txtIdConsCli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeConsCli)
                    .addComponent(txtNomeConsCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsutarClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInfoConsClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pnlPrincipalAltExcClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirClientes))
                .addGap(35, 35, 35))
        );

        pnlPrincipalAltExcClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterarClientes, btnExcluirClientes});

        pnlPrincipalAltExcClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsutarClientes, txtIdConsCli, txtNomeConsCli});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalAltExcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltExcEmailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltExcEmailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltExcEmailCliActionPerformed

    private void btnConsutarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutarClientesActionPerformed
        if(txtIdConsCli.getText().trim().equals("") || txtNomeConsCli.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Informe um dos parametros para cosulta");
        }
        else{
            if(txtIdConsCli.getText().trim().equals("")){
                String nomeCliConsul = txtNomeConsCli.getText();
            }
            else{
                int idCliCons = Integer.parseInt(txtNomeConsCli.getText());
            }
        }
    }//GEN-LAST:event_btnConsutarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlteExclClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlteExclClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSexoCliente;
    private javax.swing.JButton btnAlterarClientes;
    private javax.swing.JButton btnConsutarClientes;
    private javax.swing.JButton btnExcluirClientes;
    private javax.swing.JComboBox<String> cbbAltExcECCli;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltExcCepCli;
    private javax.swing.JLabel lblAltExcCidCli;
    private javax.swing.JLabel lblAltExcComplCli;
    private javax.swing.JLabel lblAltExcCpfCli;
    private javax.swing.JLabel lblAltExcDataNascCli;
    private javax.swing.JLabel lblAltExcECCli;
    private javax.swing.JLabel lblAltExcEmailCli;
    private javax.swing.JLabel lblAltExcIdCli;
    private javax.swing.JLabel lblAltExcLograCli;
    private javax.swing.JLabel lblAltExcNomeCli;
    private javax.swing.JLabel lblAltExcNumCepCli;
    private javax.swing.JLabel lblAltExcSexCli;
    private javax.swing.JLabel lblAltExcTelCli;
    private javax.swing.JLabel lblIdConsCli;
    private javax.swing.JLabel lblInfoAltExcClientes;
    private javax.swing.JLabel lblNomeConsCli;
    private javax.swing.JLabel lblTituloAltExcClientes;
    private javax.swing.JPanel pnlInfoConsClientes;
    private javax.swing.JPanel pnlPrincipalAltExcClientes;
    private javax.swing.JPanel pnlTituloAltExcClientes;
    private javax.swing.JRadioButton rbtAltExcSexFemCli;
    private javax.swing.JRadioButton rbtAltExcSexMascCli;
    private javax.swing.JTable tblAltExcClientes;
    private javax.swing.JFormattedTextField txtAltExcCepCli;
    private javax.swing.JTextField txtAltExcCidCli;
    private javax.swing.JTextField txtAltExcComplCli;
    private javax.swing.JFormattedTextField txtAltExcCpfCli;
    private javax.swing.JFormattedTextField txtAltExcDataNascCli;
    private javax.swing.JTextField txtAltExcEmailCli;
    private javax.swing.JTextField txtAltExcIdCli;
    private javax.swing.JTextField txtAltExcLograCli;
    private javax.swing.JTextField txtAltExcNomeCli;
    private javax.swing.JTextField txtAltExcNumCepCli;
    private javax.swing.JFormattedTextField txtAltExcTelCli;
    private javax.swing.JTextField txtIdConsCli;
    private javax.swing.JTextField txtNomeConsCli;
    // End of variables declaration//GEN-END:variables
}
